<?php
echo "<div class='juego' id='" . $juego['nombre'] . "'>";
echo '<div class="header-juego">';
  echo '<img src="data:' . $juego['tipo_imagen'] . ';base64,' . $juego['imagen'] . '" alt="Portada del ' . $juego['nombre'] . '" loading="lazy " >';
echo '</div>';
echo '<div class="contenido-juego">';
  echo '<div class="contenedor-titulo-juego">';
    echo '<p class="titulo-juego">' . $juego['nombre'] . '</p>';
    echo '<div class="subrallado"></div>';
  echo '</div>';
  echo '<p class="descripcion-juego">' . $juego['descripcion'] . '</p>';
  echo '<div>';
    echo '<p class="contenido-subtitulo">plataforma</p>';
    echo '<ul class="plataformas-juego">';
      echo '<li>' . $_SESSION['plataformas'][$juego['id_plataforma']] . '</li>';
    echo '</ul>';
  echo '</div>'; 
  echo '<div>';
    echo '<p class="url-juego contenido-subtitulo">pagina oficial</p>';
    echo '<ul class="url-juego">';
      echo '<li class="url">';
        echo '<a href="'. $juego['url'] .'" target="_blank">'. $juego['url'] .'</a>';
      echo '</li>';
    echo '</ul>';
  echo '</div>';
  echo '<div>';
    echo '<p class="contenido-subtitulo">genero</p>';
    echo '<ul class="generos-juego">';
      echo '<li>' . $_SESSION['generos'][$juego['id_genero']] . '</li>';
    echo '</ul>';
  echo '</div>';  
echo '</div>';    
echo '</div>';